### ISSUE TITLE
Braces in Markdown indistinguishable from JSX braces

### ISSUE THREAD

**Issue by steveluscher** [osnr/markdown-it-jsx#1]
Right now, we don't have a way of distinguishing between a set of braces that you want to use to evaluate a JavaScript expression and a literal set of braces. Consider the following Markdown:

``````
# Hello World

<MyComponent onClick={() => alert('hello')}>Say “hello.”</MyComponent>

And now for a code block:

```
function() {
  alert('hello');
}
```
``````

We produce the following output:

``` jsx
<h1>Hello World</h1>
<MyComponent onClick={() => alert('hello')}>Say “hello.”</MyComponent>
<p>And now for a code block:</p>
<pre><code>function() {
  alert('hello');
}</code></pre>
```

If I treat that output as JSX now, I can't distinguish between the braces in `onClick={() => alert('hello')}` and the braces in `function() { … }`. If I escape all the braces, my `onClick` will not work. If I escape none of the braces, then my code block will be reduced to `function()` because the `{ alert('hello'); }` will get evaluated as an expression that returns `undefined`.

**Comment by Xiphe** [comment]
this can be fixed by overwriting the highlight parser and ["quoting as a plain JS string"](https://github.com/facebook/react/issues/1545#issuecomment-43417130) as proposed by @spicyj

Will provide a PR

**Comment by osnr** [comment]
Sorry, I didn't have this project on watch!

Will look at and probably merge + publish #2 and #3 later today or tomorrow.

**Comment by osnr** [comment]
published, thank you all :)
